In [9]:
import numpy as np

In [11]:
l = [2, 4, 6, 8, 10]
l

[2, 4, 6, 8, 10]

In [19]:
a = np.array([7,3,1,87,6, 18])
a

array([ 7,  3,  1, 87,  6, 18])

In [14]:
type(a)

numpy.ndarray

In [15]:
type(l)

list

In [18]:
print(np.where(a == 9))

(array([3], dtype=int64),)


In [20]:
np.sort(a)

array([ 1,  3,  6,  7, 18, 87])

In [24]:
listb = [[1,2,3,4],[5,6,7,8]]
listb

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [41]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
b.shape

(3, 4)

In [39]:
c = np.zeros((2,3,4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [40]:
c.shape

(2, 3, 4)

In [37]:
d = np.zeros((2,3,4,5))
d

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [38]:
d.shape

(2, 3, 4, 5)

In [46]:
from numpy import random
x = random.rand(2,3,4)
x

array([[[0.29629873, 0.88463642, 0.53960439, 0.02109971],
        [0.19282423, 0.64922583, 0.90960508, 0.07976229],
        [0.20529333, 0.50053634, 0.49376556, 0.33383777]],

       [[0.79584522, 0.77727252, 0.39720512, 0.37776551],
        [0.76327823, 0.19085093, 0.72675405, 0.41990994],
        [0.99196627, 0.30936942, 0.14565304, 0.11755836]]])